### ISSUE TITLE
Develop an initial OML to Bikeshed capability

### ISSUE THREAD

**Issue by melaasar** [opencaesar/oml-tools#1]
## User Story
As an ontology developer, I want to be able to generate Bikeshed spec corresponding to my ontologies, so I can publish them.

## Acceptance Criteria
- [x] Have a CLI that can take an input folder (of OML models), and output folder, and a publishing URL, and generates Bikeshed specs corresponding to them

**Comment by dwagmuse** [comment]
- [ ] Directly asserted properties of Concepts
- [ ] Properties asserted on supertypes of Concepts
- [ ] Concept taxonomy graph?
