### ISSUE TITLE
[BUG] - cross referencing is not seeing all the specializations

### ISSUE THREAD

**Issue by dwagmuse** [opencaesar/oml-tools#10]
## Description
Specific problem I noticed is that mission:Component also specializes project:SuppliedElement. This specialization appears in the documentation for project module but not in the mission. This is probably because project imports mission and so the project specializations are not visible in mission.  

Might need to use bundles to allow forward scoping of documentation while avoiding having to consider every possible specialization. Maybe just add a link to where the concept is specialized in other vocabularies?

## Steps to Reproduce
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

## Expected Behavior
A clear and concise description of what should be the expected behavior.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by melaasar** [comment]
When I look at the docs, I see this:
<img width="837" alt="Screen Shot 2021-07-22 at 3 56 11 PM" src="https://user-images.githubusercontent.com/5720252/126719207-fb954939-92c0-4da7-afc9-0228a3e5e0bb.png">

Isn't this what you expect?

**Comment by dwagmuse** [comment]
looks good now
