### ISSUE TITLE
[BUG] - Documentation - Tools named 'oml-*' but in README.md the gradle plugin is referred to as 'owl-*'

### ISSUE THREAD

**Issue by JWT007** [opencaesar/oml-tools#11]
## Description
The README.MD documentation refers to 'owl-bikeshed' but the tool is called 'oml-bikeshed'.
Same for the 'oml-merge' subproject.

```
cd oml-merge
gradlew.bat owl-merge:run --args="..."
```

**Comment by melaasar** [comment]
Fixed the typos. Thanks!
