### ISSUE TITLE
[BUG] - incorrect batch commmands in publish.bat

### ISSUE THREAD

**Issue by mprather** [opencaesar/oml-tools#22]
## Description
The oml2bikeshed task is generating commands with the wrong syntax for .bat files.

## Steps to Reproduce
Using the FireSat project as the starting point, run ".\gradlew generateDocs"

Result:
The gradle task fails with the following:
> Task :generateDocs
Caching disabled for task ':generateDocs' because:
  Build cache is disabled
Task ':generateDocs' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Starting process 'command 'build/bikeshed/publish.bat''. Working directory: C:\src\firesat Command: build/bikeshed/publish.bat
Successfully started process 'command 'build/bikeshed/publish.bat''

C:\src\firesat>cd "$(dirname "$0")"
The system cannot find the path specified.

## Expected Behavior
No failures for windows users

## Additional Context
Looking at the publish.bat file that is generated, it seems that generator is not differentiating between linux shell and dos syntax.  The windows script cannot change into the correct folder b/c it is using bash commands and variable syntax. This should be a rather easy fix (use ‘cd  “%~dp0”’ instead) when creating the batch file but however it seems OS differentiation is driven by the gradle build task rather than the generation code. Perhaps the script generation should omit the cd command and instead place that responsibility with the gradle task?  

For info on variable substitution, see https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-xp/bb490909(v=technet.10)?redirectedfrom=MSDN.

## Relevant screenshots
![image](https://user-images.githubusercontent.com/25933462/126709726-3cc0e765-78fe-4b16-a368-9ae266219643.png)

**Comment by paulgaspardo** [comment]
Yeah, `cd "$(dirname "$0")"` is definitely not valid batch script.

I'll try the suggested `cd "%~dp0"`

**Comment by melaasar** [comment]
This was addressed in the v0.9.4 release
