### ISSUE TITLE
Generate documentation for imported external ontologies

### ISSUE THREAD

**Issue by dwagmuse** [opencaesar/oml-tools#3]
## User Story
Generate documentation for imported external ontologies

## Detailed Description

Generate documentation for imported external ontologies such as dublin core and xmlschema that link to their external reference documentation on the web. 
Initially, this can generate a document for each graph that has links to the external description.
Later on we can figure out how to skip creating an intermediate document for these ontologies and just replace all references to them with links to the external docs.
## Acceptance Criteria

* Every imported external graph has a link to the external documentation for that schema
* Every data type and property defined as references to external ontologies has a link to the specific documentation for that item

## Sub-task List
- [ ] Update oml2bikeshed
- [ ] Update oml ontologies as needed

**Comment by dwagmuse** [comment]
Current ontologies contain only iri references to external definitions. Some of them (xmlschema at least) have separate documentation at a different url that I would like to link to, but we can't obviously derive the documentation link from iri. So I think we need to add annotations to the ontologies (either description or about).

**Comment by dwagmuse** [comment]
will oml let me put dc annotations on the dc terminology description?

**Comment by melaasar** [comment]
Yes, you can put annotations whose annotation property is accessible to the current ontology, directly or through import. So, a dc:description can be an annotation on the dc vocabulary.

**Comment by melaasar** [comment]
Does the dc:description solution in the previous comment address the requirement?

**Comment by dwagmuse** [comment]
yes

**Comment by melaasar** [comment]
Good, so closing this one. If you still think the solution offered is insufficient, feel free to reoopn.
